### ISSUE TITLE
Fix solenoids when coming out of test mode

### ISSUE THREAD

**Issue by CodingKoopa** [longwood564/Robot2021#9]
When coming out of test mode, the double solenoids are set to `kOff`, breaking the `toggle()` method. There are a couple of solutions to this:
- Somehow run code when initializing teleop and/or autonomous. If we do this I would probably extend `CommandScheduler` and/or `TimedRobot` to make it really work. In order to do this, though, I would need to see that there's more than just the solenoid that has to be initialized more than just in the constructor.
- We don't rely on `toggle()`, and keep track of the state ourselves.

Unless there comes up more things that we are going to want to init more than once, I'm liking the latter option more.

**Comment by RyanStyron** [comment]
I certainly believe the latter of the two options is better, and less complex of a resolution.

**Comment by CodingKoopa** [comment]
Yeah, it is seeming like attaching things to teleop/auto is somewhat fundamentally not compatible with command based.

**Comment by RyanStyron** [comment]
Resolved in the `Add commands to initialize modes` PR (#10).
